name: "Build & Release Android Only"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release Android
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'


      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release #--split-per-abi

#      - name: Upload APK to Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/release/*"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload APK & AAB to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
