name: "Build & Release Android Only"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release Android
    runs-on: windows-latest  # Or `ubuntu-latest` if you prefer Linux

    steps:
      - uses: actions/checkout@v4  # Update to latest Node.js 20-compatible version
      - uses: actions/setup-java@v4  # Update to latest Node.js 20-compatible version
        with:
          distribution: 'zulu'
          java-version: '17'


      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.11.0-0.0.pre.123'  # Specify a known Flutter version here
          channel: 'stable'
          architecture: x64


      - run: flutter pub get

      - run: flutter build apk --release --split-per-abi

      - name: Upload APK to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}
